"""Create User and Customer tables

Revision ID: 0f5a3fbf9d5c
Revises: 
Create Date: 2025-10-23 06:17:56.787339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f5a3fbf9d5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('employee_id', sa.String(length=8), nullable=False),
    sa.Column('employee_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index('idx_user_employee_id', 'users', ['employee_id'], unique=False)
    op.create_table('customers',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('customer_contact', sa.String(), nullable=True),
    sa.Column('customer_address', sa.String(), nullable=True),
    sa.Column('managed_by', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['managed_by'], ['users.employee_id'], ),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_index('idx_customer_customer_id', 'customers', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_customer_customer_id', table_name='customers')
    op.drop_table('customers')
    op.drop_index('idx_user_employee_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###